USE `periode`;
CREATE TABLE Periodensystem(
                               `id` int NOT NULL,
                               `Symbol` varchar(50) NULL,
                               `Name` varchar(50) NULL,
                               `Kategorie` varchar(50) NULL,
                               `Masse` varchar(50) NULL
);
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (1, N'H ', N'Wasserstoff', N'Nichtmetal', N'1.01      ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (2, N'He ', N'Helium ', N'Edelgas ', N'4         ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (3, N'Li ', N'Lithium ', N'Alkalimetall', N'6.94      ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (4, N'Be ', N'Beryllium ', N'Erdkalimetal', N'9.01      ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (5, N'B ', N'Bor ', N'Halbmetal', N'10.81     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (6, N'C ', N'Kohlenstoff', N'Nichtmetal', N'12.01     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (7, N'N ', N'Stickstoff', N'Nichtmetal', N'14.01     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (8, N'O ', N'Sauerstoff', N'Nichtmetal', N'16        ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (9, N'F ', N'Fluor ', N'Halogen ', N'19        ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (10, N'Ne ', N'Neon ', N'Edelgas ', N'20.18     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (11, N'Na ', N'Natrium ', N'Alkalimetall', N'22.99     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (12, N'Mg ', N'Magnesium ', N'Erdkalimetal', N'24.3      ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (13, N'Al ', N'Aluminium ', N'Metall ', N'26.98     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (14, N'Si ', N'Silicium ', N'Halbmetal', N'28.09     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (15, N'P ', N'Phosphor3 ', N'Nichtmetal', N'30.97     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (16, N'S ', N'Schwefel', N'Nichtmetal', N'32.07     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (17, N'Cl ', N'Chlor ', N'Halogen ', N'35.45     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (18, N'Ar ', N'Argon ', N'Edelgas ', N'39.94     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (19, N'K ', N'Kalium ', N'Alkalimetall', N'39.1      ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (20, N'Ca ', N'Calcium ', N'Erdkalimetal', N'40.08     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (21, N'Sc ', N'Scandium ', N'?bergangsmetal', N'44.96     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (22, N'Ti ', N'Titan ', N'?bergangsmetal', N'47.88     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (23, N'V ', N'Vanadium ', N'?bergangsmetal', N'50.94     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (24, N'Cr ', N'Chrom ', N'?bergangsmetal', N'52        ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (25, N'Mn ', N'Mangan ', N'?bergangsmetal', N'54.9      ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (26, N'Fe ', N'Eisen', N'?bergangsmetal', N'55.85     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (27, N'Co ', N'Cobalt ', N'?bergangsmetal', N'58.93     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (28, N'Ni ', N'Nickel ', N'?bergangsmetal', N'58.69     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (29, N'Cu ', N'Kupfer', N'?bergangsmetal', N'63.55     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (30, N'Zn ', N'Zink ', N'?bergangsmetal', N'65.39     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (31, N'Ga ', N'Gallium ', N'Metall ', N'69.72     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (32, N'Ge ', N'Germanium ', N'Halbmetal', N'72.61     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (33, N'As ', N'Arsen ', N'Halbmetal', N'74.92     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (34, N'Se ', N'Selen ', N'Halbmetal', N'78.96     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (35, N'Br ', N'Brom ', N'Halogen ', N'79.9      ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (36, N'Kr ', N'Krypton ', N'Edelgas ', N'83.8      ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (37, N'Rb ', N'Rubidium ', N'Alkalimetall', N'85.45     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (38, N'Sr ', N'Strontium ', N'Erdkalimetal', N'87.62     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (39, N'Y ', N'Yttrium ', N'?bergangsmetal', N'88.91     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (40, N'Zr ', N'Zirconium ', N'?bergangsmetal', N'91.22     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (41, N'Nb ', N'Niob ', N'?bergangsmetal', N'92.91     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (42, N'Mo ', N'Molybdän ', N'?bergangsmetal', N'95.94     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (43, N'Tc ', N'Technetium ', N'?bergangsmetal', N'98.91     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (44, N'Ru ', N'Ruthenium ', N'?bergangsmetal', N'101.07    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (45, N'Rh ', N'Rhodium ', N'?bergangsmetal', N'102.91    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (46, N'Pd ', N'Palladium ', N'?bergangsmetal', N'106.42    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (47, N'Ag ', N'Silber', N'?bergangsmetal', N'107.87    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (48, N'Cd ', N'Cadmium ', N'?bergangsmetal', N'112.41    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (49, N'In ', N'Indium ', N'Metall ', N'114.82    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (50, N'Sn ', N'Zinn', N'Metall ', N'118.71    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (51, N'Sb ', N'Antimon', N'Halbmetal', N'121.75    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (52, N'Te ', N'Tellur ', N'Halbmetal', N'127.6     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (53, N'I ', N'Iod ', N'Halogen ', N'126.9     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (54, N'Xe ', N'Xenon ', N'Edelgas ', N'131.29    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (55, N'Cs ', N'Caesium ', N'Alkalimetall', N'132.91    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (56, N'Ba ', N'Barium ', N'Erdkalimetal', N'137.33    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (57, N'La ', N'Lanthan ', N'?bergangsmetal', N'138.9     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (58, N'Ce ', N'Cer ', N'Lanthanoid', N'140.11    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (59, N'Pr ', N'Praseodym ', N'Lanthanoid', N'140.91    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (60, N'Nd ', N'Neodym ', N'Lanthanoid', N'144.24    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (61, N'Pm ', N'Pro­methium ', N'Lanthanoid', N'146.92    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (62, N'Sm ', N'Samarium ', N'Lanthanoid', N'150.36    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (63, N'Eu ', N'Europium ', N'Lanthanoid', N'151.96    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (64, N'Gd ', N'Gadolinium ', N'Lanthanoid', N'157.25    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (65, N'Tb ', N'Terbium ', N'Lanthanoid', N'158.93    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (66, N'Dy ', N'Dysprosium ', N'Lanthanoid', N'162.5     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (67, N'Ho ', N'Holmium ', N'Lanthanoid', N'164.93    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (68, N'Er ', N'Erbium ', N'Lanthanoid', N'167.26    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (69, N'Tm ', N'Thulium ', N'Lanthanoid', N'168.93    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (70, N'Yb ', N'Ytterbium ', N'Lanthanoid', N'173.04    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (71, N'Lu ', N'Lutetium ', N'Lanthanoid', N'174.97    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (72, N'Hf ', N'Hafnium ', N'?bergangsmetal', N'178.49    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (73, N'Ta ', N'Tantal ', N'?bergangsmetal', N'180.95    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (74, N'W ', N'Wolfram ', N'?bergangsmetal', N'183.85    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (75, N'Re ', N'Rhenium ', N'?bergangsmetal', N'186.21    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (76, N'Os ', N'Osmium ', N'?bergangsmetal', N'190.23    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (77, N'Ir ', N'Iridium ', N'?bergangsmetal', N'192.22    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (78, N'Pt ', N'Platin ', N'?bergangsmetal', N'195.08    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (79, N'Au ', N'Gold', N'?bergangsmetal', N'196.97    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (80, N'Hg ', N'Quecksilber', N'?bergangsmetal', N'200.59    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (81, N'Tl ', N'Thallium ', N'Metall ', N'204.38    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (82, N'Pb ', N'Blei', N'Metall ', N'207.2     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (83, N'Bi ', N'Bismut', N'Metall ', N'208.98    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (84, N'Po ', N'Polonium ', N'Metall ', N'208.98    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (85, N'At ', N'Astat ', N'Halogen ', N'209.99    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (86, N'Rn ', N'Radon ', N'Edelgas ', N'222.02    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (87, N'Fr ', N'Francium ', N'Alkalimetall', N'223.02    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (88, N'Ra ', N'Radium ', N'Erdkalimetal', N'226.03    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (89, N'Ac ', N'Actinium ', N'?bergangsmetal', N'227.03    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (90, N'Th ', N'Thorium ', N'Actinoid ', N'232.04    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (91, N'Pa ', N'Protactinium', N'Actinoid ', N'231.04    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (92, N'U ', N'Uran ', N'Actinoid ', N'238.03    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (93, N'Np ', N'Neptunium ', N'Actinoid ', N'237.05    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (94, N'Pu ', N'Plutonium ', N'Actinoid ', N'244.06    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (95, N'Am ', N'Americium ', N'Actinoid ', N'243.06    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (96, N'Cm ', N'Curium ', N'Actinoid ', N'247.07    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (97, N'Bk ', N'Berkelium ', N'Actinoid ', N'247.07    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (98, N'Cf ', N'Californium ', N'Actinoid ', N'251.08    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (99, N'Es ', N'Einsteinium ', N'Actinoid ', N'252.08    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (100, N'Fm ', N'Fermium ', N'Actinoid ', N'257.1     ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (101, N'Md ', N'Mendelevium', N'Actinoid ', N'258       ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (102, N'No ', N'Nobelium ', N'Actinoid ', N'259       ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (103, N'Lr ', N'Lawrencium', N'Actinoid ', N'260       ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (104, N'Rf ', N'Rutherfordium', N'?bergangsmetal', N'261.11    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (105, N'Db ', N'Dubnium ', N'?bergangsmetal', N'262.11    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (106, N'Sg ', N'Seaborgium ', N'?bergangsmetal', N'263.12    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (107, N'Bh ', N'Bohrium ', N'?bergangsmetal', N'262.12    ');
INSERT Periodensystem (`id`, `Symbol`, `Name`, `Kategorie`, `Masse`) VALUES (108, N'Hs ', N'Hassium ', N'?bergangsmetal', N'265       ');